config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :email_links, only: [:create]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  use_doorkeeper
  use_doorkeeper_openid_connect
  resources :users, only: %i[show edit update]
  namespace :admin do
    resources :users
    put 'users/deactivate/:id(.:format)', to: 'users#deactivate', as: :deactivate_user
    put 'users/activate/:id(.:format)', to: 'users#activate', as: :activate_user
  end
  post 'invite' => 'users#invite', as: :create_invitation
  post 'invite_self' => 'users#invite_self', as: :create_self_invitation
  get 'invite' => 'users#magic_login', as: :email_link

  namespace :api do
    namespace :v1 do
      get 'users/me'
    end
  end

  as :user do
    delete '/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  get '/login' => 'application#login', as: :new_session
  root to: 'users#show'
end

app/views/layouts/doorkeeper/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= t('doorkeeper.layouts.admin.title') %></title>
  <%= stylesheet_link_tag "doorkeeper/admin/application" %>
  <%= stylesheet_link_tag "doorkeeper/admin/custom" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
  <%= link_to t('doorkeeper.layouts.admin.nav.oauth2_provider'), oauth_applications_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if request.path == oauth_applications_path %>">
        <%= link_to t('doorkeeper.layouts.admin.nav.applications'), oauth_applications_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if request.path == admin_users_path %>">
        <%= link_to t('doorkeeper.layouts.admin.nav.users'), admin_users_path, class: 'nav-link' %>
      </li>
      <% if respond_to?(:root_path) %>
        <li class="nav-item">
          <%= link_to t('doorkeeper.layouts.admin.nav.home'), root_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<div class="doorkeeper-admin container">
  <%- if flash[:notice].present? %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end -%>
  <%- if flash[:alert].present? %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end -%>

  <%= yield %>
</div>
</body>
</html>

app/views/layouts/doorkeeper/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alfred</title>
      <%= stylesheet_link_tag "doorkeeper/application" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>
      .alfred {
        height: 800px;
        position: relative;
      }
    </style>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <div class="main">
        <!-- Sing in  Form -->
      <section class="sign-in">
        <div class="container">
          <%=yield %>
        </div>
      </section>
    </div>
  </body>
</html>