config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :email_links, only: [:create]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  use_doorkeeper
  use_doorkeeper_openid_connect
  resources :users, only: %i[show edit update]
  namespace :admin do
    resources :users
    put 'users/deactivate/:id(.:format)', to: 'users#deactivate', as: :deactivate_user
    put 'users/activate/:id(.:format)', to: 'users#activate', as: :activate_user
  end
  post 'invite' => 'users#invite', as: :create_invitation
  post 'invite_self' => 'users#invite_self', as: :create_self_invitation
  get 'invite' => 'users#magic_login', as: :email_link

  namespace :api do
    namespace :v1 do
      get 'users/me'
    end
  end

  as :user do
    delete '/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  get '/login' => 'application#login', as: :new_session
  root to: 'users#show'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :app_admissions, dependent: :destroy
  has_many :oauth_applications, through: :app_admissions
  accepts_nested_attributes_for :app_admissions

  validates :dob, presence: true

  after_commit :add_default_avatar, on: %i[create update]

  devise :omniauthable, :lockable, :trackable

  has_one_attached :avatar

  def admin?
    is_admin
  end

  def add_default_avatar
    return if avatar.attached?

    avatar.attach(
      io: File.open(Rails.root.join('app', 'assets', 'images', 'default.png')),
      filename: 'default.jpg',
      content_type: 'image/png'
    )
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_user, only: %i[show edit update destroy deactivate activate]
    before_action :set_application_names, only: %i[edit new]
    before_action :prevent_empty_params, only: %i[update]

    layout 'doorkeeper/admin'

    def index
      @users = User.all.includes(:oauth_applications)
      @active_users = User.all.where(deactivated_at: nil)
      @deactivated_users = User.all.where.not(deactivated_at: nil)
    end

    def show; end

    def edit; end

    def new
      @user = User.new
    end

    def update
      if @user.update(user_params)
        redirect_to admin_user_path(@user),
                    notice: 'Profile was successfully updated.'
      else
        render :edit
      end
    end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to @user, notice: 'User was successfully created.'
      else
        render :new
      end
    end

    def destroy
      flash[:notice] = 'User was deleted.' if @user.destroy
      redirect_to admin_users_path
    end

    def deactivate
      if @user.update(oauth_application_ids: [], deactivated_at: DateTime.now)
        redirect_to admin_user_path(@user),
                    notice: 'User was successfully deactivated.'
      else
        redirect_back(fallback_location: root_path)
      end
    end

    def activate
      if @user.update(deactivated_at: nil)
        redirect_to admin_user_path(@user),
                    notice: 'User was successfully activated.'
      else
        redirect_back(fallback_location: root_path)
      end
    end

    private

    def prevent_empty_params
      params[:user][:oauth_application_ids] ||= []
    end

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :dob, :avatar,
                                   :email, oauth_application_ids: [])
    end

    def set_application_names
      @applications = OauthApplication.select(:name, :id)
      @user_application_names = @user&.oauth_applications&.pluck(:name) || []
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      skip_before_action :authenticate_user!
      before_action :doorkeeper_authorize!

      def me
        render json: {
          id: current_resource_owner.id,
          uid: current_resource_owner.uid,
          first_name: current_resource_owner.first_name,
          last_name: current_resource_owner.last_name,
          email: current_resource_owner.email,
          dob: current_resource_owner.dob,
          avatar: current_resource_owner.avatar.service_url
        }.to_json
      end

      private

      def current_resource_owner
        User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  # callbacks controller
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_action :authenticate_user!

    before_action :guild_member?

    def discord
      user = from_omniauth(request.env['omniauth.auth'])
      sign_in(user)

      redirect_to_back_or_edit(user)
    end

    private

    def guild_member?
      token = request.env['omniauth.auth'].credentials.token
      response = HTTParty.get('https://discord.com/api/users/@me/guilds',
                              headers: { 'Authorization': "Bearer #{token}" })
      return if response.any? { |h| h['id'] == ENV.fetch('DISCORD_SERVER_ID') }

      redirect_to new_session_url, notice: t('non_cg_alert')
    end

    def from_omniauth(auth)
      User.find_or_initialize_by(email: auth.info.email).tap do |user|
        user.uid = auth.uid
        fill_fullname(auth, user) if [user.first_name, user.last_name].any?(&:blank?)

        user.save
      end
    end

    def fill_fullname(auth, user)
      fullname = auth.info.name.split(/[.\s]/, 2)
      user.first_name, user.last_name = fullname.size == 2 ? fullname : [*fullname, '']
    end

    def redirect_to_back_or_edit(user)
      if [user.first_name, user.last_name].any?(&:blank?) && user.sign_in_count <= 1
        flash[:alert] = t('update_profile')
        redirect_to edit_user_path(user)
      else
        redirect_to after_sign_in_path_for(user)
      end
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]
  skip_before_action :authenticate_user!, only: %i[invite_self magic_login]
  skip_before_action :store_user_location!, only: :edit

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to after_sign_in_path_for(@user), notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  def invite
    UserInviter.new(params[:email]).invite
    flash[:notice] = 'The link was sent'
    redirect_to admin_users_path
  end

  def invite_self
    if UserInviter.new(params[:email]).invite
      flash[:notice] = 'The link was sent to your email'
    else
      flash[:alert] = 'This e-mail is not present in our DB'
    end
    redirect_to root_path
  end

  def magic_login
    user = User.where(magic_link_token: params[:token]).first
    if user
      user.update(magic_link_token: nil)
      sign_in(user, scope: :user)
      redirect_to user_path(user)
    else
      flash[:alert] = 'Your token is invalid'
      redirect_to root_path
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :dob, :avatar, :email)
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
  def app_access_checkboxes(app_list:, current_apps:)
    app_list.map do |app|
      "<div class='custom-control custom-checkbox'>
          <input type='checkbox'
             name='user[oauth_application_ids][]'
             class='custom-control-input'
             id='app_#{app.id}'
             value='#{app.id}'
             #{'checked' if current_apps.include?(app.name)}>
             #{label_tag("app_#{app.id}", app.name,
                         class: 'custom-control-label')}
      </div>"
    end.join(' ').html_safe
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_admin_form.html.erb
<%= form_with(model: user, url: form_url, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'user-form' %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'user-form' %>
  </div>

  <div class="form-group">
    <%= form.label :dob %>
    <div>
      <%= form.date_select :dob, start_year: 1983, end_year: 2005, class: 'user-form' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, class: 'user-form' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <div>
      <%= form.text_field :email, class: 'user-form', style: 'width: 30rem;' %>
    </div>
  </div>

  <%= app_access_checkboxes(app_list: applications, current_apps: user_application_names) %>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/users/edit.html.erb
<h3>Editing User</h3>

<%= render 'admin_form', user: @user, form_url: admin_user_path(@user),
                         applications: @applications, user_application_names: @user_application_names %>

app/views/admin/users/index.html.erb
<div class="border-bottom mb-4">
  <h1><%= t('.title') %></h1>
</div>

<p><%= link_to t('.new'), new_admin_user_path, class: 'btn btn-success' %></p>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= t('.email') %></th>
    <th class="text-center"><%= t('.access') %></th>
  </tr>
  </thead>
  <tbody>
  <% @active_users.each do |user| %>
    <tr id="user_<%= user.id %>">
      <td class="align-middle">
        <%= link_to user.email, admin_user_path(user) %>
      </td>

      <td class="align-middle text-center">
        <% user.oauth_applications.each do |app| %>
          <span class="badge badge-info"> <%= app.name %> </span>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br />

<% unless @deactivated_users.empty? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="text-center"><%= t('.deactivated') %></th>
      </tr>
    </thead>
    <tbody>
      <% @deactivated_users.each do |user| %>
        <tr>
          <td class="align-middle">
            <%= link_to user.email, admin_user_path(user) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'admin_form', user: @user, form_url: admin_users_path,
                         applications: @applications, user_application_names: @user_application_names %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p>
  <%=image_tag @user.avatar %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<p>
  <strong>Dob:</strong>
  <%= @user.dob %>
</p>

<p>
  <strong>Access granted to:</strong>
  <%= @user.oauth_applications.pluck(:name).join(', ') %>
</p>

<div class='d-flex'>
<% if allowed_to?(:deactivate?, @user) %>
  <%= button_to t('.deactivate'), admin_deactivate_user_path(@user), method: :put, class: 'user-show-button btn btn-danger' %>
<% elsif allowed_to?(:activate?, @user) %>
  <%= button_to t('.activate'), admin_activate_user_path(@user), method: :put, class: 'user-show-button btn btn-success' %>
<% end %>
  
<% if allowed_to?(:edit_access?, @user) %>
  <%= button_to t('.edit'), edit_admin_user_path(@user), method: :get, class: 'user-show-button btn btn-primary' %>
<% end %>

<% if allowed_to?(:delete?, @user) %>
  <%= button_to t('.delete'), admin_user_path(@user), method: :delete, class: 'user-show-button btn btn-danger' %>
<% end %>

<% if allowed_to?(:invite_from_ui?, @user) %>
  <%= button_to t('.invite'), create_invitation_path(email: @user.email), method: :post, class: 'user-show-button btn btn-success' %>
<% end %>
</div>